version: "3.9"

services:

  instances_generator:
    # Instances generator
    profiles:
      - instances_generator
    command: '/app/heuristics/run_instances_generator.sh'
    build:
      dockerfile: DOCKERFILE
      context: .
    volumes:
      - ./data:/data:rw
      - ./integer_linear_programs:/app/integer_linear_programs:ro

  optimizer:
    profiles:
      - gurobi
      - optimizer
    build:
      dockerfile: gurobi.dockerfile
      context: .
    command: "python -u /home/gurobi/src/gurobi_optimizer.py --instances_file /data/instances.csv --limit 3600 --results s3://kcmc-heuristic/2022-06 --lock KCMC"
    environment:
      GRB_CLIENT_LOG: 3
      PYTHONPATH: "/home/gurobi/src"
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${AWS_SECRET_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SHARDING: ${SHARDING}
    volumes:
      - ${GUROBI_LICENSE_FILE}:/opt/gurobi/gurobi.lic:ro
      - ./data/results:/results:rw
      - ./data:/data:ro
      - ./src:/home/gurobi/src:ro
      - ./builds:/app:ro

  fast_optimizer:
    profiles:
      - fast_optimizer
    build:
      dockerfile: gurobi.dockerfile
      context: .
    command: "/home/gurobi/src/run_optimizer.sh"
    environment:
      PYTHONPATH: "/home/gurobi/src"
    volumes:
      - ./data/results:/results:rw
      - ./data:/data:ro
      - ./src:/home/gurobi/src:ro
      - ./builds:/app:ro

  parser:
    profiles:
      - parser
    build:
      dockerfile: notebook.dockerfile
      context: .
    entrypoint: ["python", "-u", "/home/gurobi/src/parse_results.py"]
    environment:
      PYTHONPATH: "/home/gurobi/src"
    volumes:
      - ./data/results:/results:ro
      - ./data:/data:ro
      - ./src:/home/gurobi/src:rw
      - ./builds:/app:ro

  notebook:
    profiles:
      - notebook
    build:
      dockerfile: notebook.dockerfile
      context: .
    ports:
      - "8888:8888"
    environment:
      GRB_CLIENT_LOG: 3
      PYTHONPATH: "/src"
    volumes:
      - ${GUROBI_LICENSE_FILE}:/opt/gurobi/gurobi.lic:ro
      - ./data:/data:ro
      - ./src:/src:ro
      - ./builds:/app:ro
      - ./analysis:/home/gurobi/0_analysis:rw
