version: "3.9"

services:

  heuristics:
    # Instances generator and heuristic optimizer
    command: '/app/run_heuristics.sh'
    build:
      dockerfile: DOCKERFILE
      context: .
    image: ${DOCKER_REPOSITORY}:latest
    environment:
      RESULTS_TARGET: 's3://kcmc-heuristic/2023/heuristic'
    volumes:
      - ./data:/data:rw
      - ./integer_linear_programs:/app/integer_linear_programs:ro

  gurobi:
    # GUROBI optimizer in given instances
    build:
      dockerfile: DOCKERFILE
      context: .
    image: ${DOCKER_REPOSITORY}:latest
    # command: '/app/run_gurobi.sh "KCMC;100 100 1;300 50 100;237599344;END" 1 1 single-flow -p 4'
    # command: '/app/run_gurobi.sh "KCMC;100 100 1;300 50 100;237599344;END" 1 1 single-flow -p 4 -e reuse-dinic -a i44i68i69i77i79i88i89i91i92i95i97i98i99'
    # command: '/app/run_gurobi.sh "KCMC;100 100 1;300 50 100;237599344;END" 1 1 multi-flow -p 4'
    command: '/app/run_gurobi.sh "KCMC;100_100_1;300_50_100;237599344;END" 1 1 multi-flow -p 4 -e reuse-dinic -a i44i68i69i77i79i88i89i91i92i95i97i98i99'
    environment:
      GRB_VERSION: 9.5.1
      GRB_CLIENT_LOG: 3
      PYTHONPATH: "/home/gurobi/src"
      RESULTS_TARGET: 's3://kcmc-heuristic/2023/gurobi'
    volumes:
      - ./integer_linear_programs:/app/integer_linear_programs:ro
      - ./kcmc_gurobi.lic:/opt/gurobi/gurobi.lic:ro

  notebook:
    profiles:
      - notebook
    build:
      dockerfile: notebook.dockerfile
      context: .
    ports:
      - "8888:8888"
    environment:
      GRB_CLIENT_LOG: 3
      PYTHONPATH: "/src"
    volumes:
      - ./kcmc_gurobi.lic:/opt/gurobi/gurobi.lic:ro
      - ./data:/data:ro
      - ./src:/src:ro
