version: "3.9"

services:

  compiler:
    # Dockerized compiler environment
    profiles:
      - compiler
    build:
      dockerfile: compiler.dockerfile
      context: .
    command: bash /app/src/compiler_entrypoint.sh
    volumes:
      - ./CMakeLists.txt:/app/CMakeLists.txt:ro
      - ./src:/app/src:ro
      - ./builds:/app/builds:rw

  generator:
    # Instances generator
    profiles:
      - generator
    command: '/src/run_instance_generator.sh'
    build:
      dockerfile: instance_generator.dockerfile
      context: .
    volumes:
      - ./data:/data:rw
      - ./src:/src:ro

  optimizer:
    profiles:
      - gurobi
      - optimizer
    build:
      dockerfile: gurobi.dockerfile
      context: .
    command: "python -u /home/gurobi/src/gurobi_optimizer.py --instances_file /data/instances.csv --limit 3600 --results s3://kcmc-heuristic/2022-06 --lock KCMC"
    environment:
      GRB_CLIENT_LOG: 3
      PYTHONPATH: "/home/gurobi/src"
      AWS_DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${AWS_SECRET_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ${GUROBI_LICENSE_FILE}:/opt/gurobi/gurobi.lic:ro
      - ./data:/data:ro
      - ./src:/home/gurobi/src:ro
      - ./analysis/results:/results:rw
      - ./builds:/app:ro
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 16G

  notebook:
    profiles:
      - notebook
    build:
      dockerfile: notebook.dockerfile
      context: .
    ports:
      - "8888:8888"
    environment:
      GRB_CLIENT_LOG: 3
      PYTHONPATH: "/home/gurobi/0_analysis/src"
    volumes:
      - ${GUROBI_LICENSE_FILE}:/opt/gurobi/gurobi.lic:ro
      - ./data:/data:rw
      - /media/zeff/Peixe/DATA:/data/dynamodb_objs:ro
      - ./builds:/app:ro
      - ./analysis:/home/gurobi/0_analysis:rw
      - ./src:/home/gurobi/0_analysis/src:ro

  dataviz:
    profiles:
      - dataviz
      - notebook
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./dataviz/index.html:/usr/share/nginx/html/index.html:ro
      - ./dataviz/css:/usr/share/nginx/html/css:ro
      - ./dataviz/fonts:/usr/share/nginx/html/fonts:ro
      - ./dataviz/js:/usr/share/nginx/html/js:ro
      - ./dataviz/stylesheets:/usr/share/nginx/html/stylesheets:ro
      - ./data/visualizations:/usr/share/nginx/html/datasets:ro
